### ISSUE TITLE
Question with run code 

### ISSUE THREAD

**Issue by szyvcdc** [ObliviateRickLin/PLOP#1]
Dear RicLin，

Is your code complete? When I run ‘main_model’, some errors are displayed, such as ‘density_network’ is incomplete, can you give some simple guidance? Thank you very much for your reply.

**Comment by ObliviateRickLin** [comment]
Thank you for reaching out. To clarify, the implementation of the Gaussian density network component is indeed not complete. This repository was initially created to assist a colleague with their research, which **necessitated leaving parts of the code unfilled to allow for more flexible adaptation** to their specific needs.

Essentially, that part is just a fully connected neural network, and I encourage you to tailor the architecture to fit your own output requirements. Also, if you find the repository useful, I will contemplate further development (like fill in this part later on).

Please feel free to continue contacting me should you have any more questions or need further assistance.

Cheers,
Rick

**Comment by szyvcdc** [comment]
Thank you for your reply and the whole work. I have followed you and your further work, and saw that part of your code is marked with Chinese. If it is convenient, could you add it to your wechat for further communication
